# Copyright 2017-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# curl -H "xos-username: admin@opencord.org" -H "xos-password: letmein" -X POST --data-binary @fabric-config.yaml http://192.168.99.100:30007/run

tosca_definitions_version: tosca_simple_yaml_1_0
imports:
  - custom_types/switch.yaml
  - custom_types/switchport.yaml
  - custom_types/portinterface.yaml
  - custom_types/fabricipaddress.yaml
description: Configures fabric switches and related ports
topology_template:
  node_templates:
    switch#leaf1:
      type: tosca.nodes.Switch
      properties:
        driver: ofdpa3
        ipv4Loopback: 192.168.0.201
        ipv4NodeSid: 17
        isEdgeRouter: True
        name: leaf1
        ofId: of:0000000000000001
        routerMac: 00:00:02:01:06:01

    # Setup a fabric switch port
    port#port1:
      type: tosca.nodes.SwitchPort
      properties:
        portId: 1
      requirements:
        - switch:
            node: switch#leaf1
            relationship: tosca.relationships.BelongsToOne

    # Setup a fabric switch port interface
    interface#interface1:
      type: tosca.nodes.PortInterface
      properties:
        name: port1
      requirements:
        - port:
            node: port#port1
            relationship: tosca.relationships.BelongsToOne

    # Setup a fabric switch port interface
    ipaddress#ipaddress1:
      type: tosca.nodes.FabricIpAddress
      properties:
        ip: 192.168.0.254/24
        description: some ip address
      requirements:
        - interface:
            node: interface#interface1
            relationship: tosca.relationships.BelongsToOne

    # Setup a fabric switch port with host_learning disabled
    port#port2:
      type: tosca.nodes.SwitchPort
      properties:
        portId: 2
        host_learning: false
      requirements:
        - switch:
            node: switch#leaf1
            relationship: tosca.relationships.BelongsToOne